
default: &default
  adapter: postgresql
  encoding: unicode
  host:  <%= ENV["host_postgres"] %>
  port: <%= ENV["port_postgres"] %>
  username: <%= ENV["username_postgres"] %>
  password: <%= ENV["password_postgres"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sventas_development

test:
  <<: *default
  database: sventas_test


production:
  <<: *default
  database: sventas_production
  username: sventas
  password: <%= ENV["SVENTAS_DATABASE_PASSWORD"] %>
